<h1 align="center">Numpy - 01 - Conhecendo a biblioteca e nossos dados</h1>  

- Criar arrays com sequências numéricas.  
- Carregar arquivos.  
- Verificar as dimensões de um array.  
- Realizar a transposição de um array.  

In [1]:
import numpy as np

O arquivo `csv` tem as colunas com nomes, mas array só possui um tipo. Pra isso usamos o parâmetro `use_cols` com um arange (exclusivo): 1 a 88.  

$7 \cdot 12 + 3 = 87$  

Podemos importar tanto localmente, com o `apples.csv` quanto via `url`. Via `url`, vai criar localmente uma cópia da fonte. Por isso, optei por fabricar os csv's.

In [2]:
data = np.loadtxt("apples.csv", delimiter=",", usecols=np.arange(1, 88, 1))

In [3]:
data.ndim, data.size, data.shape, data.T

(2,
 522,
 (6, 87),
 array([[  1.2013,  79.72  ,  42.67  ,  62.55  ,  48.26  ,  71.25  ],
        [  2.2013,  81.08  ,  44.37  ,  62.73  ,  51.01  ,  71.35  ],
        [  3.2013,  79.68  ,  44.73  ,  63.43  ,  50.91  ,  70.9   ],
        [  4.2013,  79.8   ,  46.75  ,  63.83  ,  53.94  ,  71.92  ],
        [  5.2013,  80.63  ,      nan,  66.06  ,  61.27  ,  72.91  ],
        [  6.2013,  80.8   ,  51.59  ,  69.22  ,  65.44  ,  74.39  ],
        [  7.2013,  80.28  ,  57.8   ,  72.07  ,  56.51  ,  73.1   ],
        [  8.2013,  78.99  ,  62.14  ,  69.31  ,  53.    ,  70.24  ],
        [  9.2013,  76.77  ,  56.76  ,  65.18  ,  43.87  ,  69.12  ],
        [ 10.2013,  76.09  ,  50.85  ,  62.13  ,  42.12  ,  68.98  ],
        [ 11.2013,  76.36  ,  46.43  ,  64.17  ,  43.98  ,  68.58  ],
        [ 12.2013,  77.16  ,  46.73  ,  65.5   ,  44.66  ,  69.5   ],
        [  1.2014,  77.5   ,  45.85  ,  66.85  ,  47.73  ,  70.14  ],
        [  2.2014,  79.03  ,  49.25  ,  68.38  ,  52.31  ,  70.58  ],


## 01 - Questão
Um colega pediu para você carregar uma base de dados e verificar o número de linhas e colunas do arquivo carregado. Ele estava com dúvidas se o número total de linhas havia sido carregado.

Como determinar as dimensões corretas de um array?

> Para responder essa pergunta você precisará do dataset. Você pode usar a opção `skiprows=1` para pular a primeira linha do arquivo.

In [4]:
dataset = np.loadtxt("bytebank.csv", skiprows=1, delimiter=',', dtype=float)
dataset

array([[3.00000e+00, 5.18217e+03],
       [        nan,         nan],
       [1.00000e+00, 5.06000e+03],
       [2.00000e+00, 5.12072e+03],
       [5.00000e+00, 5.30729e+03],
       [6.00000e+00, 5.37097e+03],
       [7.00000e+00, 5.43543e+03],
       [8.00000e+00, 5.50065e+03],
       [9.00000e+00, 5.56666e+03],
       [1.00000e+01, 5.63346e+03],
       [1.10000e+01, 5.70106e+03],
       [1.20000e+01, 5.76947e+03]])

## Dataset Citrus


In [5]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.loadtxt("citrus.csv", delimiter=',',skiprows=1, usecols=np.arange(1, 5), dtype=float)

array([[  2.96,  86.76, 172.  ,  85.  ],
       [  3.91,  88.05, 166.  ,  78.  ],
       [  4.42,  95.17, 156.  ,  81.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ],
       [ 15.92, 260.14, 142.  ,  72.  ],
       [ 16.45, 261.51, 152.  ,  74.  ]], shape=(10000, 4))