In [1]:
# 1
import numpy as np

In [4]:
# 2 Print the numpy version and the configuration (★☆☆)
print(np.__version__, np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/VictorCampos/anaconda3/Library/include
    lib directory: C:/Users/VictorCampos/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  h

In [3]:
# 3 Create a null vector
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 4 How to find the memory size of any array 
vetor = np.array([1.0,5.0,2.0,0.0])
print(vetor.itemsize)


8


In [ ]:
# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [10]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
null_vector = np.zeros(10)
null_vector[4] = 1
print(
    null_vector
)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)
vetor7 = np.arange(10,50)
vetor7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
# 8 Reverse a vector (first element becomes last) (★☆☆)
vetor7 = vetor7[::-1]
vetor7

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [ ]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [51]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
questao10 = np.array([1,2,0,0,4,0])
np.where(questao10 == 0)

(array([2, 3, 5], dtype=int64),)

In [67]:
# 11. Create a 3x3 identity matrix (★☆☆)
print(f"{np.identity(3)}\n")

## 
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
# 12. Create a 3x3x3 array with random values (★☆☆)
np.random.random((3,3,3))

array([[[0.73353771, 0.43703693, 0.09428162],
        [0.02494862, 0.97031369, 0.75358111],
        [0.10707582, 0.85978936, 0.27054912]],

       [[0.07386671, 0.95237788, 0.53974033],
        [0.61654839, 0.38890692, 0.53665628],
        [0.46478652, 0.26546549, 0.73895326]],

       [[0.63576893, 0.18135021, 0.72980029],
        [0.50221843, 0.98885947, 0.49295433],
        [0.87545651, 0.17693547, 0.48826365]]])